export const ANIMATIONS = {
  Death: "CharacterArmature|Death",
  Gun_Shoot: "CharacterArmature|Gun_Shoot",
  HitRecieve: "CharacterArmature|HitRecieve",
  HitRecieve_2: "CharacterArmature|HitRecieve_2",
  Idle: "CharacterArmature|Idle",
  Idle_Gun: "CharacterArmature|Idle_Gun",
  Idle_Gun_Pointing: "CharacterArmature|Idle_Gun_Pointing",
  Idle_Gun_Shoot: "CharacterArmature|Idle_Gun_Shoot",
  Idle_Neutral: "CharacterArmature|Idle_Neutral",
  Idle_Sword: "CharacterArmature|Idle_Sword",
  Interact: "CharacterArmature|Interact",
  Kick_Left: "CharacterArmature|Kick_Left",
  Kick_Right: "CharacterArmature|Kick_Right",
  Punch_Left: "CharacterArmature|Punch_Left",
  Punch_Right: "CharacterArmature|Punch_Right",
  Roll: "CharacterArmature|Roll",
  Run: "CharacterArmature|Run",
  Run_Back: "CharacterArmature|Run_Back",
  Run_Left: "CharacterArmature|Run_Left",
  Run_Right: "CharacterArmature|Run_Right",
  Run_Shoot: "CharacterArmature|Run_Shoot",
  Sword_Slash: "CharacterArmature|Sword_Slash",
  Walk: "CharacterArmature|Walk",
  Wave: "CharacterArmature|Wave",
};
